export enum StakeButtonError {
  INSUFFICIENT_BALANCE_RBC = 'INSUFFICIENT_BALANCE_RBC',
  EMPTY_AMOUNT = 'EMPTY_AMOUNT',
  LESS_THEN_MINIMUM = 'LESS_THEN_MINIMUM',
  NULL = 'NULL',
  NEED_APPROVE = 'NEED_APPROVE',
  STAKING_CLOSED = 'STAKING_CLOSED'
}
