import { INSTANT_TRADES_PROVIDERS } from '@app/shared/models/instant-trade/instant-trade-providers';
import { SUPPORTED_CROSS_CHAIN_BLOCKCHAINS } from '../models/supported-cross-chain-blockchain';

export const popularDexByChain = {
  [SUPPORTED_CROSS_CHAIN_BLOCKCHAINS[0]]: [
    INSTANT_TRADES_PROVIDERS.UNISWAP_V2,
    INSTANT_TRADES_PROVIDERS.ONEINCH
  ],
  [SUPPORTED_CROSS_CHAIN_BLOCKCHAINS[1]]: [
    INSTANT_TRADES_PROVIDERS.PANCAKESWAP,
    INSTANT_TRADES_PROVIDERS.ONEINCH
  ],
  [SUPPORTED_CROSS_CHAIN_BLOCKCHAINS[2]]: [
    INSTANT_TRADES_PROVIDERS.SUSHISWAP,
    INSTANT_TRADES_PROVIDERS.ONEINCH
  ],
  [SUPPORTED_CROSS_CHAIN_BLOCKCHAINS[3]]: [
    INSTANT_TRADES_PROVIDERS.JOE,
    INSTANT_TRADES_PROVIDERS.PANGOLIN
  ],
  [SUPPORTED_CROSS_CHAIN_BLOCKCHAINS[4]]: [
    INSTANT_TRADES_PROVIDERS.SPOOKYSWAP,
    INSTANT_TRADES_PROVIDERS.SPIRITSWAP
  ],
  [SUPPORTED_CROSS_CHAIN_BLOCKCHAINS[5]]: [
    INSTANT_TRADES_PROVIDERS.SOLARBEAM,
    INSTANT_TRADES_PROVIDERS.SUSHISWAP
  ],
  [SUPPORTED_CROSS_CHAIN_BLOCKCHAINS[6]]: [
    INSTANT_TRADES_PROVIDERS.SUSHISWAP,
    INSTANT_TRADES_PROVIDERS.VIPER
  ]
};
