export enum TRADE_STATUS {
  NOT_INITIATED,
  DISABLED,
  LOADING,
  READY_TO_APPROVE,
  APPROVE_IN_PROGRESS,
  READY_TO_SWAP,
  SWAP_IN_PROGRESS,
  OLD_TRADE_DATA,
  READY_TO_BUY_NATIVE,
  BUY_NATIVE_IN_PROGRESS
}
