export enum TradeStatus {
  DISABLED = 'DISABLED',
  LOADING = 'LOADING',
  READY_TO_APPROVE = 'READY_TO_APPROVE',
  APPROVE_IN_PROGRESS = 'APPROVE_IN_PROGRESS',
  READY_TO_SWAP = 'READY_TO_SWAP',
  SWAP_IN_PROGRESS = 'SWAP_IN_PROGRESS',
  OLD_TRADE_DATA = 'OLD_TRADE_DATA'
}
