export enum RecentTradeStatus {
  PENDING = 'PENDING',
  WAITING_FOR_CONFIRMATION = 'WAITING_FOR_CONFIRMATION',
  WAITING_FOR_FUNDS_RELEASE = 'WAITING_FOR_FUNDS_RELEASE',
  SUCCESS = 'SUCCESS',
  FAIL = 'FAIL'
}
