import { BLOCKCHAIN_NAME } from '@shared/models/blockchain/blockchain-name';
import { INSTANT_TRADE_PROVIDER } from '@features/swaps/shared/models/instant-trade-provider';

export const WHITELIST_PROVIDERS = {
  [BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN]: [
    INSTANT_TRADE_PROVIDER.PANCAKESWAP,
    INSTANT_TRADE_PROVIDER.SUSHISWAP,
    INSTANT_TRADE_PROVIDER.ONEINCH
  ],
  [BLOCKCHAIN_NAME.POLYGON]: [
    INSTANT_TRADE_PROVIDER.QUICKSWAP,
    INSTANT_TRADE_PROVIDER.SUSHISWAP,
    INSTANT_TRADE_PROVIDER.ONEINCH
  ],
  [BLOCKCHAIN_NAME.FANTOM]: [
    INSTANT_TRADE_PROVIDER.SPIRITSWAP,
    INSTANT_TRADE_PROVIDER.SPOOKYSWAP,
    INSTANT_TRADE_PROVIDER.SUSHISWAP
  ],
  [BLOCKCHAIN_NAME.AVALANCHE]: [
    INSTANT_TRADE_PROVIDER.JOE,
    INSTANT_TRADE_PROVIDER.PANGOLIN,
    INSTANT_TRADE_PROVIDER.SUSHISWAP
  ],
  [BLOCKCHAIN_NAME.HARMONY]: [INSTANT_TRADE_PROVIDER.SUSHISWAP, INSTANT_TRADE_PROVIDER.VIPER],
  [BLOCKCHAIN_NAME.MOONRIVER]: [INSTANT_TRADE_PROVIDER.SUSHISWAP],
  [BLOCKCHAIN_NAME.ARBITRUM]: [INSTANT_TRADE_PROVIDER.SUSHISWAP, INSTANT_TRADE_PROVIDER.ONEINCH]
};
