import { BLOCKCHAIN_NAME, BlockchainName, TRADE_TYPE, TradeType } from 'rubic-sdk';

export const WHITELIST_PROVIDERS: Partial<Record<BlockchainName, TradeType[]>> = {
  [BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN]: [
    TRADE_TYPE.PANCAKE_SWAP,
    TRADE_TYPE.SUSHI_SWAP,
    TRADE_TYPE.ONE_INCH,
    TRADE_TYPE.PARA_SWAP,
    TRADE_TYPE.OPEN_OCEAN,
    TRADE_TYPE.DODO,
    TRADE_TYPE.ZRX
  ],
  [BLOCKCHAIN_NAME.POLYGON]: [
    TRADE_TYPE.QUICK_SWAP,
    TRADE_TYPE.SUSHI_SWAP,
    TRADE_TYPE.ONE_INCH,
    TRADE_TYPE.PARA_SWAP,
    TRADE_TYPE.OPEN_OCEAN,
    TRADE_TYPE.DODO,
    TRADE_TYPE.HONEY_SWAP,
    TRADE_TYPE.ZRX
  ],
  [BLOCKCHAIN_NAME.FANTOM]: [
    TRADE_TYPE.SPIRIT_SWAP,
    TRADE_TYPE.SPOOKY_SWAP,
    TRADE_TYPE.SUSHI_SWAP,
    TRADE_TYPE.OPEN_OCEAN,
    TRADE_TYPE.PARA_SWAP,
    TRADE_TYPE.ZRX
  ],
  [BLOCKCHAIN_NAME.AVALANCHE]: [
    TRADE_TYPE.JOE,
    TRADE_TYPE.PANGOLIN,
    TRADE_TYPE.SUSHI_SWAP,
    TRADE_TYPE.PARA_SWAP,
    TRADE_TYPE.OPEN_OCEAN,
    TRADE_TYPE.ZRX
  ],
  [BLOCKCHAIN_NAME.HARMONY]: [TRADE_TYPE.SUSHI_SWAP, TRADE_TYPE.VIPER_SWAP],
  [BLOCKCHAIN_NAME.MOONRIVER]: [TRADE_TYPE.SUSHI_SWAP, TRADE_TYPE.DODO],
  [BLOCKCHAIN_NAME.ARBITRUM]: [
    TRADE_TYPE.SUSHI_SWAP,
    TRADE_TYPE.ONE_INCH,
    TRADE_TYPE.OPEN_OCEAN,
    TRADE_TYPE.DODO
  ]
};
