import { BLOCKCHAIN_NAME } from '@shared/models/blockchain/blockchain-name';
import { INSTANT_TRADES_PROVIDERS } from '@shared/models/instant-trade/instant-trade-providers';

export const WHITELIST_PROVIDERS = {
  [BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN]: [
    INSTANT_TRADES_PROVIDERS.PANCAKESWAP,
    INSTANT_TRADES_PROVIDERS.SUSHISWAP,
    INSTANT_TRADES_PROVIDERS.ONEINCH
  ],
  [BLOCKCHAIN_NAME.POLYGON]: [
    INSTANT_TRADES_PROVIDERS.QUICKSWAP,
    INSTANT_TRADES_PROVIDERS.SUSHISWAP,
    INSTANT_TRADES_PROVIDERS.ONEINCH
  ],
  [BLOCKCHAIN_NAME.FANTOM]: [
    INSTANT_TRADES_PROVIDERS.SPIRITSWAP,
    INSTANT_TRADES_PROVIDERS.SPOOKYSWAP,
    INSTANT_TRADES_PROVIDERS.SUSHISWAP
  ],
  [BLOCKCHAIN_NAME.AVALANCHE]: [
    INSTANT_TRADES_PROVIDERS.JOE,
    INSTANT_TRADES_PROVIDERS.PANGOLIN,
    INSTANT_TRADES_PROVIDERS.SUSHISWAP
  ],
  [BLOCKCHAIN_NAME.HARMONY]: [INSTANT_TRADES_PROVIDERS.SUSHISWAP, INSTANT_TRADES_PROVIDERS.VIPER],
  [BLOCKCHAIN_NAME.MOONRIVER]: [INSTANT_TRADES_PROVIDERS.SUSHISWAP],
  [BLOCKCHAIN_NAME.ARBITRUM]: [INSTANT_TRADES_PROVIDERS.SUSHISWAP, INSTANT_TRADES_PROVIDERS.ONEINCH]
};
