import { BLOCKCHAIN_NAME } from 'src/app/shared/models/blockchain/BLOCKCHAIN_NAME';
import { INSTANT_TRADES_PROVIDER } from 'src/app/shared/models/instant-trade/INSTANT_TRADES_PROVIDER';

export const defaultSlippageTolerance = {
  [BLOCKCHAIN_NAME.ETHEREUM]: {
    [INSTANT_TRADES_PROVIDER.ONEINCH]: 2,
    [INSTANT_TRADES_PROVIDER.UNISWAP]: 2,
    [INSTANT_TRADES_PROVIDER.SUSHISWAP]: 2
  },
  [BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN]: {
    [INSTANT_TRADES_PROVIDER.ONEINCH]: 2,
    [INSTANT_TRADES_PROVIDER.PANCAKESWAP]: 2,
    [INSTANT_TRADES_PROVIDER.SUSHISWAP]: 2
  },
  [BLOCKCHAIN_NAME.POLYGON]: {
    [INSTANT_TRADES_PROVIDER.ONEINCH]: 2,
    [INSTANT_TRADES_PROVIDER.QUICKSWAP]: 2,
    [INSTANT_TRADES_PROVIDER.SUSHISWAP]: 2
  },
  [BLOCKCHAIN_NAME.HARMONY]: {
    [INSTANT_TRADES_PROVIDER.ONEINCH]: 2,
    [INSTANT_TRADES_PROVIDER.QUICKSWAP]: 2,
    [INSTANT_TRADES_PROVIDER.SUSHISWAP]: 2
  },
  [BLOCKCHAIN_NAME.AVALANCHE]: {
    [INSTANT_TRADES_PROVIDER.SUSHISWAP]: 2,
    [INSTANT_TRADES_PROVIDER.PANGOLIN]: 2,
    [INSTANT_TRADES_PROVIDER.JOE]: 2
  }
};
