import { BLOCKCHAIN_NAME } from '@shared/models/blockchain/blockchain-name';
import { INSTANT_TRADE_PROVIDER } from '@shared/models/instant-trade/instant-trade-provider';

export const DEFAULT_SLIPPAGE_TOLERANCE = {
  [BLOCKCHAIN_NAME.ETHEREUM]: {
    [INSTANT_TRADE_PROVIDER.ONEINCH]: 2,
    [INSTANT_TRADE_PROVIDER.UNISWAP_V2]: 2,
    [INSTANT_TRADE_PROVIDER.UNISWAP_V3]: 2,
    [INSTANT_TRADE_PROVIDER.SUSHISWAP]: 2,
    [INSTANT_TRADE_PROVIDER.ZRX]: 2
  },
  [BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN]: {
    [INSTANT_TRADE_PROVIDER.ONEINCH]: 2,
    [INSTANT_TRADE_PROVIDER.PANCAKESWAP]: 2,
    [INSTANT_TRADE_PROVIDER.SUSHISWAP]: 2
  },
  [BLOCKCHAIN_NAME.POLYGON]: {
    [INSTANT_TRADE_PROVIDER.ONEINCH]: 2,
    [INSTANT_TRADE_PROVIDER.QUICKSWAP]: 2,
    [INSTANT_TRADE_PROVIDER.SUSHISWAP]: 2,
    [INSTANT_TRADE_PROVIDER.ALGEBRA]: 2
  },
  [BLOCKCHAIN_NAME.HARMONY]: {
    [INSTANT_TRADE_PROVIDER.ONEINCH]: 2,
    [INSTANT_TRADE_PROVIDER.QUICKSWAP]: 2,
    [INSTANT_TRADE_PROVIDER.SUSHISWAP]: 2
  },
  [BLOCKCHAIN_NAME.AVALANCHE]: {
    [INSTANT_TRADE_PROVIDER.SUSHISWAP]: 2,
    [INSTANT_TRADE_PROVIDER.PANGOLIN]: 2,
    [INSTANT_TRADE_PROVIDER.JOE]: 2
  },
  [BLOCKCHAIN_NAME.MOONRIVER]: {
    [INSTANT_TRADE_PROVIDER.SOLARBEAM]: 2,
    [INSTANT_TRADE_PROVIDER.SUSHISWAP]: 2
  },
  [BLOCKCHAIN_NAME.FANTOM]: {
    [INSTANT_TRADE_PROVIDER.SUSHISWAP]: 2,
    [INSTANT_TRADE_PROVIDER.SPOOKYSWAP]: 2,
    [INSTANT_TRADE_PROVIDER.SPIRITSWAP]: 2
  },
  [BLOCKCHAIN_NAME.SOLANA]: {
    [INSTANT_TRADE_PROVIDER.RAYDIUM]: 2
  }
};
