import { CROSS_CHAIN_TRADE_TYPE, CrossChainTradeType } from '@cryptorubic/core';

export const NEED_TRUSTLINE_TRANSIT_TOKENS: Partial<Record<CrossChainTradeType, string>> = {
  [CROSS_CHAIN_TRADE_TYPE.RUBIC_STELLAR_API]:
    'USDC-GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN'
};
