import { BLOCKCHAIN_NAME, BlockchainName } from 'rubic-sdk';

export const blockchainsToFetch: BlockchainName[] = [];

export const blockchainsWithOnePage = [
  BLOCKCHAIN_NAME.SCROLL_SEPOLIA,
  BLOCKCHAIN_NAME.GOERLI,
  BLOCKCHAIN_NAME.ARTHERA,
  BLOCKCHAIN_NAME.ZETACHAIN,
  BLOCKCHAIN_NAME.TAIKO,
  BLOCKCHAIN_NAME.SEPOLIA,
  BLOCKCHAIN_NAME.BERACHAIN,
  BLOCKCHAIN_NAME.BLAST
  // BLOCKCHAIN_NAME.FUJI,
  // BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN_TESTNET,
  // BLOCKCHAIN_NAME.MUMBAI
];

export const iframeBlockchainsToFetch: BlockchainName[] = [
  BLOCKCHAIN_NAME.SCROLL_SEPOLIA,
  BLOCKCHAIN_NAME.GOERLI,
  BLOCKCHAIN_NAME.ARTHERA,
  BLOCKCHAIN_NAME.ZETACHAIN,
  BLOCKCHAIN_NAME.TAIKO,
  BLOCKCHAIN_NAME.SEPOLIA
  // BLOCKCHAIN_NAME.FUJI,
  // BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN_TESTNET,
  // BLOCKCHAIN_NAME.MUMBAI
];
