import { BLOCKCHAIN_NAME, BlockchainName } from 'rubic-sdk';

export const blockchainsToFetch: BlockchainName[] = [
  BLOCKCHAIN_NAME.BERACHAIN_TESTNET,
  BLOCKCHAIN_NAME.SEPOLIA,
  BLOCKCHAIN_NAME.SCROLL_SEPOLIA,
  BLOCKCHAIN_NAME.HOLESKY,
  BLOCKCHAIN_NAME.BLAST_TESTNET,
  BLOCKCHAIN_NAME.ARTHERA,
  BLOCKCHAIN_NAME.UNICHAIN_SEPOLIA_TESTNET,
  BLOCKCHAIN_NAME.SONEIUM_TESTNET,
  BLOCKCHAIN_NAME.MONAD_TESTNET
];

export const blockchainsWithOnePage: BlockchainName[] = [];
