export enum CLEARSWAP_STATUS {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  KYC_REQUIRED = 'KYC_REQUIRED',
  STUCK = 'STUCK',
  ERROR = 'ERROR',
  REVERTED = 'REVERTED',
  EXPIRED = 'EXPIRED'
}

export enum CLEARSWAP_SUB_STATUS {
  AWAITING_DEPOSIT = 'AWAITING_DEPOSIT',
  CONFIRMING = 'CONFIRMING',
  PENDING = 'PENDING',
  HIDING = 'HIDING',
  SENDING = 'SENDING',
  KYC_REQUIRED = 'KYC_REQUIRED',
  STUCK = 'STUCK',
  ERROR = 'ERROR',
  REVERTED = 'REVERTED',
  EXPIRED = 'EXPIRED'
}
