import { BLOCKCHAIN_NAME } from 'src/app/shared/models/blockchain/BLOCKCHAIN_NAME';

export type InstantTradeBlockchain = Exclude<
  BLOCKCHAIN_NAME,
  | BLOCKCHAIN_NAME.TRON
  | BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN_TESTNET
  | BLOCKCHAIN_NAME.ETHEREUM_TESTNET
  | BLOCKCHAIN_NAME.HARMONY_TESTNET
  | BLOCKCHAIN_NAME.POLYGON_TESTNET
  | BLOCKCHAIN_NAME.XDAI
>;
