import { BLOCKCHAIN_NAME } from '@shared/models/blockchain/blockchain-name';

export const STAKE_LIMIT_MAX = {
  [BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN]: 100000,
  [BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN]: 100000,
  [BLOCKCHAIN_NAME.ETHEREUM]: 100100,
  [BLOCKCHAIN_NAME.POLYGON]: 100100,
  [BLOCKCHAIN_NAME.POLYGON_TESTNET]: 100100,
  [BLOCKCHAIN_NAME.ETHEREUM_TESTNET]: 100100
};

export const STAKE_LIMIT_MIN = {
  [BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN]: 1000,
  [BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN]: 1000,
  [BLOCKCHAIN_NAME.ETHEREUM]: 1100,
  [BLOCKCHAIN_NAME.POLYGON]: 1100,
  [BLOCKCHAIN_NAME.POLYGON_TESTNET]: 1100,
  [BLOCKCHAIN_NAME.ETHEREUM_TESTNET]: 1100
};
