export enum WALLET_NAME {
  METAMASK = 'metamask',
  COIN_BASE = 'coinbase',
  WALLET_CONNECT = 'walletconnect',
  TRUST_WALLET = 'trustwallet',
  TRON_LINK = 'tronlink',
  ARGENT = 'argent',
  BITGET = 'bitget',
  PHANTOM = 'phantom',
  SOLFLARE = 'solflare',
  SAFE = 'safe',
  TOKEN_POCKET = 'tokenpocket',
  HOLD_STATION = 'holdstation',
  TON_CONNECT = 'tonconnect',
  TONKEEPER = 'tonkeeper',
  MY_TON_WALLET = 'my_ton_wallet',
  TELEGRAM_WALLET = 'telegram_wallet',
  CTRL = 'ctrl',
  SLUSH = 'slush',
  SUIET_WALLET = 'suiet',
  BEST_WALLET = 'best_wallet',
  SUI_WALLET = 'sui_wallet',
  METAMASK_SOLANA = 'metamask_solana',
  BINANCE_WALLET = 'binance_wallet',
  BACKPACK = 'backpack'
}
