export enum WALLET_NAME {
  METAMASK = 'metamask',
  COIN_BASE = 'coinbase',
  WALLET_CONNECT = 'walletconnect',
  TRUST_WALLET = 'trustwallet',
  TRON_LINK = 'tronlink',
  PHANTOM = 'phantom',
  PHANTOM_SOLANA = 'phantom_solana',
  SOLFLARE = 'solflare',
  SAFE = 'safe',
  TON_CONNECT = 'tonconnect',
  TONKEEPER = 'tonkeeper',
  MY_TON_WALLET = 'my_ton_wallet',
  TELEGRAM_WALLET = 'telegram_wallet',
  SLUSH = 'slush',
  SUIET_WALLET = 'suiet',
  BEST_WALLET = 'best_wallet',
  SUI_WALLET = 'sui_wallet',
  METAMASK_SOLANA = 'metamask_solana',
  BACKPACK = 'backpack',
  LOBSTR = 'lobstr',
  FREIGHTER = 'freighter',
  STELLAR_WALLET_CONNECT = 'stellar_wallectconnect'
}
