export enum WALLET_NAME {
  METAMASK = 'metamask',
  WALLET_LINK = 'walletlink',
  WALLET_CONNECT = 'walletconnect',
  TRUST_WALLET = 'trustwallet',
  TRON_LINK = 'tronlink',
  ARGENT = 'argent',
  BITKEEP = 'bitkeep',
  PHANTOM = 'phantom',
  SOLFLARE = 'solflare',
  SAFE = 'safe',
  TOKEN_POCKET = 'tokenpocket',
  HOLD_STATION = 'holdstation',
  TON_CONNECT = 'tonconnect',
  TONKEEPER = 'tonkeeper',
  MY_TON_WALLET = 'my_ton_wallet',
  TELEGRAM_WALLET = 'telegram_wallet',
  CTRL = 'ctrl',
  SUI_WALLET = 'sui_wallet',
  SUIET_WALLET = 'suiet',
  BEST_WALLET = 'best_wallet'
}
