export const TOKEN_FILTERS = {
  ALL_CHAINS_ALL_TOKENS: 'ALL_CHAINS_ALL_TOKENS',
  ALL_CHAINS_TRENDING: 'ALL_CHAINS_TRENDING',
  ALL_CHAINS_GAINERS: 'ALL_CHAINS_GAINERS',
  ALL_CHAINS_LOSERS: 'ALL_CHAINS_LOSERS'
} as const;

export type TokenFilter = (typeof TOKEN_FILTERS)[keyof typeof TOKEN_FILTERS];
