import { BRIDGE_TYPE, RUBIC_TO_RANGO_PROVIDERS, RangoTradeType } from 'rubic-sdk';

export const RANGO_CROSS_CHAIN_DISABLED_PROVIDERS: RangoTradeType[] = [
  RUBIC_TO_RANGO_PROVIDERS[BRIDGE_TYPE.RAINBOW],
  RUBIC_TO_RANGO_PROVIDERS[BRIDGE_TYPE.SYNAPSE],
  RUBIC_TO_RANGO_PROVIDERS[BRIDGE_TYPE.OPTIMISM_GATEWAY],
  RUBIC_TO_RANGO_PROVIDERS[BRIDGE_TYPE.ORBITER_BRIDGE],
  RUBIC_TO_RANGO_PROVIDERS[BRIDGE_TYPE.ARBITRUM_BRIDGE],
  RUBIC_TO_RANGO_PROVIDERS[BRIDGE_TYPE.IBC],
  RUBIC_TO_RANGO_PROVIDERS[BRIDGE_TYPE.SYMBIOSIS],
  RUBIC_TO_RANGO_PROVIDERS[BRIDGE_TYPE.OSMOSIS_BRIDGE],
  RUBIC_TO_RANGO_PROVIDERS[BRIDGE_TYPE.MAYA_PROTOCOL]
];
