import { CROSS_CHAIN_DEPOSIT_STATUS, CrossChainDepositStatus } from 'rubic-sdk';

export const DEPOSIT_STATUS_STEPS: [
  initialStatus: CrossChainDepositStatus,
  finishStatus: CrossChainDepositStatus
][] = [
  [CROSS_CHAIN_DEPOSIT_STATUS.WAITING, CROSS_CHAIN_DEPOSIT_STATUS.CONFIRMING],
  [CROSS_CHAIN_DEPOSIT_STATUS.CONFIRMING, CROSS_CHAIN_DEPOSIT_STATUS.EXCHANGING],
  [CROSS_CHAIN_DEPOSIT_STATUS.EXCHANGING, CROSS_CHAIN_DEPOSIT_STATUS.SENDING],
  [CROSS_CHAIN_DEPOSIT_STATUS.SENDING, CROSS_CHAIN_DEPOSIT_STATUS.FINISHED]
];
