import { ON_CHAIN_TRADE_TYPE, OnChainTradeType } from 'rubic-sdk';

export const instantTradesLabels: Record<OnChainTradeType, string> = {
  [ON_CHAIN_TRADE_TYPE.ACRYPTOS]: 'Acryptos',
  [ON_CHAIN_TRADE_TYPE.ALDRIN_EXCHANGE]: 'AldrinExchange',
  [ON_CHAIN_TRADE_TYPE.ALGEBRA]: 'Algebra',
  [ON_CHAIN_TRADE_TYPE.ALGEBRA_INTEGRAL]: 'Algebra Integral',
  [ON_CHAIN_TRADE_TYPE.ANNEX]: 'Annex',
  [ON_CHAIN_TRADE_TYPE.APE_SWAP]: 'ApeSwap',
  [ON_CHAIN_TRADE_TYPE.ARTH_SWAP]: 'ArthSwap',
  [ON_CHAIN_TRADE_TYPE.ASTRO_SWAP]: 'AstroSwap',
  [ON_CHAIN_TRADE_TYPE.AURORA_SWAP]: 'AuroraSwap',

  [ON_CHAIN_TRADE_TYPE.BABY_SWAP]: 'BabySwap',
  [ON_CHAIN_TRADE_TYPE.BASE_SWAP]: 'BaseSwap',
  [ON_CHAIN_TRADE_TYPE.BALANCER]: 'Balancer',
  [ON_CHAIN_TRADE_TYPE.BEAM_SWAP]: 'BeamSwap',
  [ON_CHAIN_TRADE_TYPE.BI_SWAP]: 'BiSwap',
  [ON_CHAIN_TRADE_TYPE.BRIDGERS]: 'Bridgers',

  [ON_CHAIN_TRADE_TYPE.CLAIM_SWAP]: 'ClaimSwap',
  [ON_CHAIN_TRADE_TYPE.CREMA_FINANCE]: 'CremaFinance',
  [ON_CHAIN_TRADE_TYPE.CRO_SWAP]: 'CroSwap',
  [ON_CHAIN_TRADE_TYPE.CRONA_SWAP]: 'CronaSwap',
  [ON_CHAIN_TRADE_TYPE.CROPPER_FINANCE]: 'CropperFinance',
  [ON_CHAIN_TRADE_TYPE.CROW_FI]: 'CrowFi',
  [ON_CHAIN_TRADE_TYPE.CRO_DEX]: 'CroDex',
  [ON_CHAIN_TRADE_TYPE.CURVE]: 'Curve',

  [ON_CHAIN_TRADE_TYPE.ELK]: 'Elk',

  [ON_CHAIN_TRADE_TYPE.DEFI_PLAZA]: 'DefiPlaza',
  [ON_CHAIN_TRADE_TYPE.DEFI_SWAP]: 'DefiSwap',
  [ON_CHAIN_TRADE_TYPE.DFYN]: 'Dfyn',
  [ON_CHAIN_TRADE_TYPE.DODO]: 'Dodo',
  [ON_CHAIN_TRADE_TYPE.DYSTOPIA]: 'Dystopia',

  [ON_CHAIN_TRADE_TYPE.HONEY_SWAP]: 'HoneySwap',

  [ON_CHAIN_TRADE_TYPE.IZUMI]: 'Izumi',

  [ON_CHAIN_TRADE_TYPE.JET_SWAP]: 'JetSwap',
  [ON_CHAIN_TRADE_TYPE.JOE]: 'Joe',
  [ON_CHAIN_TRADE_TYPE.JUPITER]: 'Jupiter',
  [ON_CHAIN_TRADE_TYPE.JUPITER_SWAP]: 'JupiterSwap',
  [ON_CHAIN_TRADE_TYPE.J_SWAP]: 'JSwap',

  [ON_CHAIN_TRADE_TYPE.KYBER_SWAP]: 'KyberSwap',

  [ON_CHAIN_TRADE_TYPE.LUA_SWAP]: 'LuaSwap',

  [ON_CHAIN_TRADE_TYPE.MAVERICK]: 'Maverick',
  [ON_CHAIN_TRADE_TYPE.MDEX]: 'MDEX',
  [ON_CHAIN_TRADE_TYPE.MESH_SWAP]: 'MeshSwap',
  [ON_CHAIN_TRADE_TYPE.MM_FINANCE]: 'MMFinance',
  [ON_CHAIN_TRADE_TYPE.MOJITO_SWAP]: 'MojitoSwap',
  [ON_CHAIN_TRADE_TYPE.MUTE_SWAP]: 'Mute',

  [ON_CHAIN_TRADE_TYPE.NET_SWAP]: 'NetSwap',

  [ON_CHAIN_TRADE_TYPE.OMNIDEX]: 'Omnidex',
  [ON_CHAIN_TRADE_TYPE.ONE_INCH]: '1inch',
  [ON_CHAIN_TRADE_TYPE.ONE_MOON]: 'OneMoon',
  [ON_CHAIN_TRADE_TYPE.ONE_SOL]: '1sol',
  [ON_CHAIN_TRADE_TYPE.OOLONG_SWAP]: 'OolongSwap',
  [ON_CHAIN_TRADE_TYPE.OPEN_OCEAN]: 'OpenOcean',
  [ON_CHAIN_TRADE_TYPE.ORCA_SWAP]: 'OrcaSwap',
  [ON_CHAIN_TRADE_TYPE.OSMOSIS_SWAP]: 'OsmosisSwap',

  [ON_CHAIN_TRADE_TYPE.PANCAKE_SWAP]: 'PancakeSwap',
  [ON_CHAIN_TRADE_TYPE.PANGOLIN]: 'Pangolin',
  [ON_CHAIN_TRADE_TYPE.PEGASYS]: 'Pegasys',
  [ON_CHAIN_TRADE_TYPE.PHOTON_SWAP]: 'PhotonSwap',
  [ON_CHAIN_TRADE_TYPE.POLYDEX]: 'Polydex',

  [ON_CHAIN_TRADE_TYPE.QUICK_SWAP]: 'QuickSwap',
  [ON_CHAIN_TRADE_TYPE.QUICK_SWAP_V3]: 'QuickSwap v3',

  [ON_CHAIN_TRADE_TYPE.RAYDIUM]: 'Raydium',
  [ON_CHAIN_TRADE_TYPE.REF_FINANCE]: 'RefFinance',
  [ON_CHAIN_TRADE_TYPE.REN_BTC]: 'renBTC',

  [ON_CHAIN_TRADE_TYPE.SABER_STABLE_SWAP]: 'SaberStableSwap',
  [ON_CHAIN_TRADE_TYPE.SAROS_SWAP]: 'SarosSwap',
  [ON_CHAIN_TRADE_TYPE.SERUM]: 'Serum',
  [ON_CHAIN_TRADE_TYPE.SHIBA_SWAP]: 'ShibaSwap',
  [ON_CHAIN_TRADE_TYPE.SMOOTHY]: 'Smoothy',
  [ON_CHAIN_TRADE_TYPE.SOLAR_BEAM]: 'SolarBeam',
  [ON_CHAIN_TRADE_TYPE.SPIRIT_SWAP]: 'SpiritSwap',
  [ON_CHAIN_TRADE_TYPE.SPL_TOKEN_SWAP]: 'SplTokenSwap',
  [ON_CHAIN_TRADE_TYPE.SPOOKY_SWAP]: 'Spooky',
  [ON_CHAIN_TRADE_TYPE.STELLA_SWAP]: 'StellaSwap',
  [ON_CHAIN_TRADE_TYPE.SURFDEX]: 'Surfdex',
  [ON_CHAIN_TRADE_TYPE.SUSHI_SWAP]: 'SushiSwap',
  [ON_CHAIN_TRADE_TYPE.SOUL_SWAP]: 'SoulSwap',
  [ON_CHAIN_TRADE_TYPE.SYMBIOSIS_SWAP]: 'Symbiosis DEX',
  [ON_CHAIN_TRADE_TYPE.SYNC_SWAP]: 'Sync Swap',

  [ON_CHAIN_TRADE_TYPE.TRADER]: 'TheTrader',
  [ON_CHAIN_TRADE_TYPE.TRISOLARIS]: 'Trisolaris',

  [ON_CHAIN_TRADE_TYPE.UBE_SWAP]: 'UbeSwap',
  [ON_CHAIN_TRADE_TYPE.UNISWAP_V2]: 'Uniswap v2',
  [ON_CHAIN_TRADE_TYPE.UNI_SWAP_V3]: 'Uniswap v3',

  [ON_CHAIN_TRADE_TYPE.VERSE]: 'Verse',
  [ON_CHAIN_TRADE_TYPE.VIPER_SWAP]: 'ViperSwap',
  [ON_CHAIN_TRADE_TYPE.VOLTAGE_SWAP]: 'VoltageSwap',
  [ON_CHAIN_TRADE_TYPE.VVS_FINANCE]: 'VVSFinance',

  [ON_CHAIN_TRADE_TYPE.WAGYU_SWAP]: 'WagyuSwap',
  [ON_CHAIN_TRADE_TYPE.WANNA_SWAP]: 'WannaSwap',
  [ON_CHAIN_TRADE_TYPE.WAULT_SWAP]: 'WaultSwap',
  [ON_CHAIN_TRADE_TYPE.WOO_FI]: 'WooFi',
  [ON_CHAIN_TRADE_TYPE.WRAPPED]: 'Wrapped',

  [ON_CHAIN_TRADE_TYPE.ZAPPY]: 'Zappy',
  [ON_CHAIN_TRADE_TYPE.ZIP_SWAP]: 'ZipSwap',
  [ON_CHAIN_TRADE_TYPE.ZRX]: '0x',

  [ON_CHAIN_TRADE_TYPE.YUZU_SWAP]: 'YuzuSwap',

  [ON_CHAIN_TRADE_TYPE.PULSEX_V1]: 'PulseX V1',
  [ON_CHAIN_TRADE_TYPE.PULSEX_V2]: 'PulseX V2',
  [ON_CHAIN_TRADE_TYPE.HORIZONDEX]: 'HorizonDEX',
  [ON_CHAIN_TRADE_TYPE.BASE_SWAP]: 'BaseSwap',
  [ON_CHAIN_TRADE_TYPE.VOOI]: 'Vooi'
};
