import { TRADE_TYPE, TradeType } from 'rubic-sdk';

export const instantTradesLabels: Record<TradeType, string> = {
  [TRADE_TYPE.ONE_INCH_ETHEREUM]: '1inch',
  [TRADE_TYPE.UNISWAP_V2]: 'Uniswap V2',
  [TRADE_TYPE.UNI_SWAP_V3_ETHEREUM]: 'Uniswap V3',
  [TRADE_TYPE.PANCAKE_SWAP]: 'Pancakeswap',
  [TRADE_TYPE.QUICK_SWAP]: 'Quickswap',
  [TRADE_TYPE.ZRX_ETHEREUM]: '0x',
  [TRADE_TYPE.PANGOLIN]: 'Pangolin',
  [TRADE_TYPE.JOE]: 'Joe',
  [TRADE_TYPE.SOLAR_BEAM]: 'Solarbeam',
  [TRADE_TYPE.SPOOKY_SWAP]: 'Spookyswap',
  [TRADE_TYPE.SPIRIT_SWAP]: 'Spiritswap',
  [TRADE_TYPE.WRAPPED]: 'Wrapped',
  [TRADE_TYPE.RAYDIUM]: 'Raydium',
  [TRADE_TYPE.ALGEBRA]: 'Algebra',
  [TRADE_TYPE.VIPER_SWAP]: 'Viperswap',
  [TRADE_TYPE.TRISOLARIS]: 'Trisolaris',
  [TRADE_TYPE.WANNA_SWAP]: 'Wannaswap',
  [TRADE_TYPE.REF_FINANCE]: 'Ref finance',
  [TRADE_TYPE.ZAPPY]: 'Zappy',
  [TRADE_TYPE.ONE_INCH_ETHEREUM]: '1inch',
  [TRADE_TYPE.ONE_INCH_ARBITRUM]: '1inch',
  [TRADE_TYPE.ONE_INCH_AVALANCHE]: '1inch',
  [TRADE_TYPE.ONE_INCH_POLYGON]: '1inch',
  [TRADE_TYPE.ONE_INCH_BSC]: '1inch',
  [TRADE_TYPE.ONE_INCH_FANTOM]: '1inch',
  [TRADE_TYPE.SUSHI_SWAP_ETHEREUM]: 'Sushiswap',
  [TRADE_TYPE.SUSHI_SWAP_ARBITRUM]: 'Sushiswap',
  [TRADE_TYPE.SUSHI_SWAP_FANTOM]: 'Sushiswap',
  [TRADE_TYPE.SUSHI_SWAP_MOONRIVER]: 'Sushiswap',
  [TRADE_TYPE.SUSHI_SWAP_AVALANCHE]: 'Sushiswap',
  [TRADE_TYPE.SUSHI_SWAP_HARMONY]: 'Sushiswap',
  [TRADE_TYPE.SUSHI_SWAP_POLYGON]: 'Sushiswap',
  [TRADE_TYPE.SUSHI_SWAP_TELOS]: 'Sushiswap',
  [TRADE_TYPE.SUSHI_SWAP_BSC]: 'Sushiswap',
  [TRADE_TYPE.UNI_SWAP_V3_POLYGON]: 'Uniswap V3',
  [TRADE_TYPE.UNI_SWAP_V3_ARBITRUM]: 'Uniswap V3'
};
