export enum LpError {
  INSUFFICIENT_BALANCE = 'INSUFFICIENT',
  EMPTY_AMOUNT = 'EMPTY_AMOUNT',
  LIMIT_GT_MAX = 'LIMIT_GT_MAX',
  LIMIT_LT_MIN = 'LIMIT_LT_MIN',
  INVALID_PERIOD = 'INVALID_PERIOD',
  NULL = 'NULL'
}
