import { BLOCKCHAIN_NAME, BlockchainName } from '@cryptorubic/core';

export const PRIVATE_SWAP_SUPPORTED_CHAIN: BlockchainName[] = [
  BLOCKCHAIN_NAME.ETHEREUM,
  BLOCKCHAIN_NAME.ARBITRUM,
  BLOCKCHAIN_NAME.OPTIMISM,
  BLOCKCHAIN_NAME.POLYGON,
  BLOCKCHAIN_NAME.BASE
];
