import { BLOCKCHAIN_NAME, BlockchainName } from '@cryptorubic/sdk';

export const disabledFromBlockchains: BlockchainName[] = [
  BLOCKCHAIN_NAME.FLOW,
  BLOCKCHAIN_NAME.IOTA,
  BLOCKCHAIN_NAME.KADENA,
  BLOCKCHAIN_NAME.KUSAMA,
  BLOCKCHAIN_NAME.MINA_PROTOCOL,
  BLOCKCHAIN_NAME.SIA,
  BLOCKCHAIN_NAME.SECRET,
  BLOCKCHAIN_NAME.WAX
];
