import { BLOCKCHAIN_NAME, BlockchainName } from 'rubic-sdk';

export const GAS_FORM_DISABLED_CHAINS: BlockchainName[] = [
  BLOCKCHAIN_NAME.AURORA,
  BLOCKCHAIN_NAME.VELAS,
  BLOCKCHAIN_NAME.SYSCOIN,
  BLOCKCHAIN_NAME.OASIS,
  BLOCKCHAIN_NAME.OKE_X_CHAIN,
  BLOCKCHAIN_NAME.KLAYTN,
  BLOCKCHAIN_NAME.TELOS,
  BLOCKCHAIN_NAME.HORIZEN_EON
];
