export enum LpFormError {
  INSUFFICIENT_BALANCE_USDC = 'INSUFFICIENT_BALANCE_USDC',
  INSUFFICIENT_BALANCE_BRBC = 'INSUFFICIENT_BALANCE_BRBC',
  EMPTY_AMOUNT = 'EMPTY_AMOUNT',
  LIMIT_GT_MAX = 'LIMIT_GT_MAX',
  LIMIT_LT_MIN = 'LIMIT_LT_MIN',
  NOT_WHITELIST_USER = 'NOT_WHITELIST_USER',
  LP_ENDED = 'LP_ENDED',
  POOL_FULL = 'POOL_FULL',
  NULL = 'NULL'
}
