export const DEPOSIT_FORM_STATE = {
  IDLE: 'IDLE',
  WAITING_FOR_SENDING_DEPOSIT: 'WAITING_FOR_SENDING_DEPOSIT',
  STATUS_TRACKING: 'STATUS_TRACKING',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED'
} as const;

export type DepositFormState = (typeof DEPOSIT_FORM_STATE)[keyof typeof DEPOSIT_FORM_STATE];
