export const DEPOSIT_FORM_STATE = {
  IDLE: 'IDLE',
  INPUT_ADDRESSES: 'INPUT_ADDRESSES',
  WAITING_FOR_SENDING_DEPOSIT: 'WAITING_FOR_SENDING_DEPOSIT',
  WAITING_FOR_SIGNING_TRANSFER: 'WAITING_FOR_SIGNING_TRANSFER',
  STATUS_TRACKING: 'STATUS_TRACKING',
  COMPLETED: 'COMPLETED'
} as const;

export type DepositFormState = (typeof DEPOSIT_FORM_STATE)[keyof typeof DEPOSIT_FORM_STATE];
