import { PrivateTradeType } from './private-trade-types';
import { PRIVATE_MODE_TAB, PrivateModeTab } from './private-mode-tab';

const HINKAL_SUPPORTED_TABS = [PRIVATE_MODE_TAB.ON_CHAIN, PRIVATE_MODE_TAB.TRANSFER];

const PRIVACYCAH_SUPPORTED_TABS = [PRIVATE_MODE_TAB.ON_CHAIN, PRIVATE_MODE_TAB.TRANSFER];

const ZAMA_SUPPORTED_ACTIONS = [PRIVATE_MODE_TAB.TRANSFER];

const RAILGUN_SUPPORTED_TABS = [PRIVATE_MODE_TAB.ON_CHAIN, PRIVATE_MODE_TAB.TRANSFER];

const CLEARSWAP_SUPPORTED_TABS = [PRIVATE_MODE_TAB.ON_CHAIN, PRIVATE_MODE_TAB.TRANSFER];

const HOUDINI_SUPPORTED_TABS = [PRIVATE_MODE_TAB.CROSS_CHAIN, PRIVATE_MODE_TAB.ON_CHAIN];

export const PRIVATE_PROVIDERS_TABS_MAP: Record<PrivateTradeType, PrivateModeTab[]> = {
  HINKAL: HINKAL_SUPPORTED_TABS,
  PRIVACY_CASH: PRIVACYCAH_SUPPORTED_TABS,
  ZAMA: ZAMA_SUPPORTED_ACTIONS,
  RAILGUN: RAILGUN_SUPPORTED_TABS,
  CLEARSWAP: CLEARSWAP_SUPPORTED_TABS,
  HOUDINI: HOUDINI_SUPPORTED_TABS
};
