import { BLOCKCHAIN_NAME } from 'rubic-sdk';

export const blockchainsList = [
  BLOCKCHAIN_NAME.ETHEREUM,
  BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN,
  BLOCKCHAIN_NAME.POLYGON,
  BLOCKCHAIN_NAME.AVALANCHE,
  BLOCKCHAIN_NAME.ARBITRUM,
  BLOCKCHAIN_NAME.FANTOM,
  BLOCKCHAIN_NAME.BOBA,
  BLOCKCHAIN_NAME.BOBA_BSC,
  BLOCKCHAIN_NAME.BOBA_AVALANCHE,
  BLOCKCHAIN_NAME.TELOS,
  BLOCKCHAIN_NAME.KAVA,
  BLOCKCHAIN_NAME.OPTIMISM,
  BLOCKCHAIN_NAME.AURORA,
  BLOCKCHAIN_NAME.OASIS,
  BLOCKCHAIN_NAME.METIS,
  BLOCKCHAIN_NAME.KLAYTN,
  BLOCKCHAIN_NAME.VELAS,
  BLOCKCHAIN_NAME.SYSCOIN,
  BLOCKCHAIN_NAME.MOONRIVER,
  BLOCKCHAIN_NAME.BITCOIN,
  BLOCKCHAIN_NAME.TRON,
  BLOCKCHAIN_NAME.BITGERT,
  BLOCKCHAIN_NAME.ETHEREUM_POW,
  BLOCKCHAIN_NAME.MOONBEAM,
  BLOCKCHAIN_NAME.FUSE,
  BLOCKCHAIN_NAME.CELO,
  BLOCKCHAIN_NAME.OKE_X_CHAIN,
  BLOCKCHAIN_NAME.HARMONY,
  BLOCKCHAIN_NAME.GNOSIS,
  BLOCKCHAIN_NAME.CRONOS

  // @TODO return after Near & Solana fix
  // BLOCKCHAIN_NAME.NEAR,
  // BLOCKCHAIN_NAME.SOLANA
];
