export const PDA_CONFIG = '4xUq6Ndzm3EKQDMdVeFHd8Rt5ZzN4swLUWYES9dB96cR';
export const PDA_POOL = '6rvuMQ7B3cwpmPHhbMGQFBsfDfkgnxiwmWxxSnkd9FjK';
export const PDA_DELEGATE = 'DrmQS74dx5yDPzAJdGpVMqpSkVP9RXFQnMQAdeo1P7mj';
export const SOLANA_CROSS_CHAIN_CONTRACT = 'r2TGRLHRtQ2Uj1CR7TCBYKgRxJi5M8FRjcqZnyQzYDB';
