import { BLOCKCHAIN_NAME } from '@shared/models/blockchain/BLOCKCHAIN_NAME';

export const FROM_TEST_BLOCKCHAINS = {
  [BLOCKCHAIN_NAME.ETHEREUM]: BLOCKCHAIN_NAME.ETHEREUM,
  [BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN]: BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN,
  [BLOCKCHAIN_NAME.POLYGON]: BLOCKCHAIN_NAME.POLYGON,
  [BLOCKCHAIN_NAME.HARMONY]: BLOCKCHAIN_NAME.HARMONY,
  [BLOCKCHAIN_NAME.AVALANCHE]: BLOCKCHAIN_NAME.AVALANCHE,
  [BLOCKCHAIN_NAME.MOONRIVER]: BLOCKCHAIN_NAME.MOONRIVER,
  [BLOCKCHAIN_NAME.FANTOM]: BLOCKCHAIN_NAME.FANTOM,
  [BLOCKCHAIN_NAME.XDAI]: BLOCKCHAIN_NAME.XDAI,
  [BLOCKCHAIN_NAME.ETHEREUM_TESTNET]: BLOCKCHAIN_NAME.ETHEREUM,
  [BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN_TESTNET]: BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN,
  [BLOCKCHAIN_NAME.POLYGON_TESTNET]: BLOCKCHAIN_NAME.POLYGON,
  [BLOCKCHAIN_NAME.HARMONY_TESTNET]: BLOCKCHAIN_NAME.HARMONY,
  [BLOCKCHAIN_NAME.AVALANCHE_TESTNET]: BLOCKCHAIN_NAME.AVALANCHE,
  [BLOCKCHAIN_NAME.SOLANA]: BLOCKCHAIN_NAME.SOLANA
};
