import { CROSS_CHAIN_TRADE_TYPE } from '@cryptorubic/core';

export const transferTradeSupportedProviders = [
  CROSS_CHAIN_TRADE_TYPE.CHANGENOW,
  CROSS_CHAIN_TRADE_TYPE.SIMPLE_SWAP,
  CROSS_CHAIN_TRADE_TYPE.CHANGELLY,
  CROSS_CHAIN_TRADE_TYPE.EXOLIX,
  CROSS_CHAIN_TRADE_TYPE.NEAR_INTENTS,
  CROSS_CHAIN_TRADE_TYPE.QUICKEX,
  CROSS_CHAIN_TRADE_TYPE.HOUDINI,
  CROSS_CHAIN_TRADE_TYPE.STEALTHEX,
  CROSS_CHAIN_TRADE_TYPE.INSTASWAP,
  CROSS_CHAIN_TRADE_TYPE.CHANGE_HERO,
  CROSS_CHAIN_TRADE_TYPE.BALTEX
] as const;

export type TransferTradeType = (typeof transferTradeSupportedProviders)[number];
