import { BLOCKCHAIN_NAME, BlockchainName, TEST_EVM_BLOCKCHAIN_NAME } from '@cryptorubic/core';

export const TIER_1_BLOCKCHAINS: BlockchainName[] = [
  BLOCKCHAIN_NAME.ETHEREUM,
  BLOCKCHAIN_NAME.ARBITRUM,
  BLOCKCHAIN_NAME.POLYGON,
  BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN,
  BLOCKCHAIN_NAME.BASE,
  BLOCKCHAIN_NAME.SOLANA,
  BLOCKCHAIN_NAME.BERACHAIN,
  BLOCKCHAIN_NAME.ZK_SYNC,
  BLOCKCHAIN_NAME.OPTIMISM,
  BLOCKCHAIN_NAME.BITCOIN
];

const EXCLUDED_TIER_2_BLOCKCHAINS = [
  ...Object.values(TEST_EVM_BLOCKCHAIN_NAME),
  ...TIER_1_BLOCKCHAINS
];

export const TIER_2_BLOCKCHAINS: BlockchainName[] = Object.values(BLOCKCHAIN_NAME).filter(
  chain => !EXCLUDED_TIER_2_BLOCKCHAINS.includes(chain)
);
