import { BLOCKCHAIN_NAME } from 'rubic-sdk';

export const CHAINS_TO_LOAD_FIRSTLY = [
  BLOCKCHAIN_NAME.ETHEREUM,
  BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN,
  BLOCKCHAIN_NAME.ARBITRUM,
  BLOCKCHAIN_NAME.POLYGON,
  BLOCKCHAIN_NAME.BASE,
  BLOCKCHAIN_NAME.ZK_SYNC
] as const;
