import { BLOCKCHAIN_NAME, EvmBlockchainName } from '@cryptorubic/core';

export const HINKAL_SUPPORTED_CHAINS: EvmBlockchainName[] = [
  BLOCKCHAIN_NAME.ETHEREUM,
  BLOCKCHAIN_NAME.ARBITRUM,
  BLOCKCHAIN_NAME.BASE,
  BLOCKCHAIN_NAME.OPTIMISM,
  BLOCKCHAIN_NAME.POLYGON
];
