import { BlockchainName, BLOCKCHAIN_NAME } from '@app/shared/models/blockchain/blockchain-name';

export const CELER_SUPPORTED_BLOCKCHAINS: BlockchainName[] = [
  BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN,
  BLOCKCHAIN_NAME.POLYGON,
  BLOCKCHAIN_NAME.FANTOM,
  BLOCKCHAIN_NAME.AVALANCHE,
  BLOCKCHAIN_NAME.ETHEREUM
];
