import { BLOCKCHAIN_NAME, BlockchainName } from '@cryptorubic/core';

export const GO_PLUS_AVAILABLE_NETWORKS: BlockchainName[] = [
  BLOCKCHAIN_NAME.ETHEREUM,
  BLOCKCHAIN_NAME.BINANCE_SMART_CHAIN,
  BLOCKCHAIN_NAME.POLYGON,
  BLOCKCHAIN_NAME.ARBITRUM,
  BLOCKCHAIN_NAME.OPTIMISM,
  BLOCKCHAIN_NAME.AVALANCHE,
  BLOCKCHAIN_NAME.FANTOM,
  BLOCKCHAIN_NAME.OKE_X_CHAIN,
  // BLOCKCHAIN_NAME.CRONOS,
  // BLOCKCHAIN_NAME.GNOSIS,
  BLOCKCHAIN_NAME.TRON,
  BLOCKCHAIN_NAME.ZK_FAIR,
  BLOCKCHAIN_NAME.BASE
];
