name: Check code quality

on:
  pull_request:
    branches:
      - master
      - rubic-beta

jobs:
  lint:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Set up packages
        run: yarn --frozen-lockfile

      - name: Run lint
        run: yarn run lint

      - name: Run lint css
        run: yarn run lint-css

      - name: Run compile
        run: yarn run compile
