export enum BLOCKCHAIN_NAME {
  ETHEREUM = 'ETH',
  BINANCE_SMART_CHAIN = 'BSC',
  POLYGON = 'POLYGON',
  XDAI = 'XDAI',
  HARMONY = 'HARMONY',
  AVALANCHE = 'AVALANCHE',
  MOONRIVER = 'MOONRIVER',
  FANTOM = 'FANTOM',
  ETHEREUM_TESTNET = 'ETH_TESTNET',
  BINANCE_SMART_CHAIN_TESTNET = 'BSC_TESTNET',
  POLYGON_TESTNET = 'POLYGON_TESTNET',
  HARMONY_TESTNET = 'HARMONY_TESTNET',
  AVALANCHE_TESTNET = 'AVALANCHE_TESTNET',
  SOLANA = 'SOL'
}

export enum DEPRECATED_BLOCKCHAIN_NAME {
  TRON = 'TRON'
}
