export enum BLOCKCHAIN_NAME {
  ETHEREUM = 'ETH',
  BINANCE_SMART_CHAIN = 'BSC',
  POLYGON = 'POLYGON',
  TRON = 'TRX',
  XDAI = 'XDAI',
  HARMONY = 'HARMONY',
  ETHEREUM_TESTNET = 'ETH_TESTNET',
  BINANCE_SMART_CHAIN_TESTNET = 'BSC_TESTNET',
  POLYGON_TESTNET = 'POLYGON_TESTNET'
}
