export enum BLOCKCHAIN_NAME {
  ETHEREUM = 'ETH',
  BINANCE_SMART_CHAIN = 'BSC',
  MATIC = 'MAT',
  ETHEREUM_TESTNET = 'ETH_TESTNET',
  BINANCE_SMART_CHAIN_TESTNET = 'BSC_TESTNET',
  MATIC_TESTNET = 'MAT_TESTNET'
}
